Updated cassandra

diff --git a/docker-compose.yaml b/docker-compose.yaml
--- a/docker-compose.yaml
+++ b/docker-compose.yaml
@@ -9,7 +9,7 @@ services:
       - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/accounts
       - SPRING_DATASOURCE_USERNAME=root
       - SPRING_DATASOURCE_PASSWORD=root
-      - JWT_SECRET=8MnKEjVM0ziVx5Bc9dHZcBgatpUtC7h9PB19ofa0GMK93OSb1DGbJtIy1Zj0DzrY
+      - JWT_SECRET=${JWT_SECRET}
     depends_on:
       - mysql
 
@@ -21,55 +21,57 @@ services:
       - mongodb
     environment:
       - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/item
-      - JWT_SECRET=8MnKEjVM0ziVx5Bc9dHZcBgatpUtC7h9PB19ofa0GMK93OSb1DGbJtIy1Zj0DzrY
+      - JWT_SECRET=${JWT_SECRET}
 
-  cassandra:
-    image: cassandra:4.1.3
-    container_name: cassandra
-    ports: [ "9042:9042" ]
-    environment:
-      - CASSANDRA_CLUSTER_NAME=dev-cluster
-      - CASSANDRA_DC=dc1
-      - CASSANDRA_RACK=rack1
-      - CASSANDRA_SEEDS=cassandra
-      - CASSANDRA_LISTEN_ADDRESS=auto
-      - CASSANDRA_RPC_ADDRESS=0.0.0.0
-      - CASSANDRA_BROADCAST_ADDRESS=cassandra
-      - CASSANDRA_BROADCAST_RPC_ADDRESS=cassandra
-      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
-    volumes:
-      - cassandra_data:/var/lib/cassandra
-    healthcheck:
-      test: [ "CMD-SHELL","cqlsh 127.0.0.1 9042 -e 'SHOW VERSION;' || exit 1" ]
-      interval: 15s
-      timeout: 10s
-      retries: 40
-      start_period: 90s
-
-  cassandra-init:
-    image: cassandra:4.1.3
-    depends_on:
-      cassandra:
-        condition: service_healthy
-    entrypoint: [ "sh","-lc" ]
-    command: >
-      echo "Ensuring keyspace 'orders'..." &&
-      until cqlsh cassandra 9042 -e "CREATE KEYSPACE IF NOT EXISTS orders WITH replication = {'class':'SimpleStrategy','replication_factor':1};";
-      do echo "Cassandra not ready, retry in 3s..."; sleep 3; done &&
-      echo "Keyspace 'orders' ready."
-    restart: "no"
+#  cassandra:
+#    image: cassandra:4.1.3
+#    container_name: cassandra
+#    ports: [ "9042:9042" ]
+#    environment:
+#      - CASSANDRA_CLUSTER_NAME=dev-cluster
+#      - CASSANDRA_DC=dc1
+#      - CASSANDRA_RACK=rack1
+#      - CASSANDRA_SEEDS=cassandra
+#      - CASSANDRA_LISTEN_ADDRESS=auto
+#      - CASSANDRA_RPC_ADDRESS=0.0.0.0
+#      - CASSANDRA_BROADCAST_ADDRESS=cassandra
+#      - CASSANDRA_BROADCAST_RPC_ADDRESS=cassandra
+#      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
+#    volumes:
+#      - cassandra_data:/var/lib/cassandra
+#    healthcheck:
+#      test: [ "CMD-SHELL","cqlsh 127.0.0.1 9042 -e 'SHOW VERSION;' || exit 1" ]
+#      interval: 15s
+#      timeout: 10s
+#      retries: 40
+#      start_period: 90s
+#
+#  cassandra-init:
+#    image: cassandra:4.1.3
+#    depends_on:
+#      cassandra:
+#        condition: service_healthy
+#    entrypoint: [ "sh","-lc" ]
+#    command: >
+#      echo "Ensuring keyspace 'orders'..." &&
+#      until cqlsh cassandra 9042 -e "CREATE KEYSPACE IF NOT EXISTS orders WITH replication = {'class':'SimpleStrategy','replication_factor':1};";
+#      do echo "Cassandra not ready, retry in 3s..."; sleep 3; done &&
+#      echo "Keyspace 'orders' ready."
+#    restart: "no"
 
   order-service:
     build: ./order-service
     ports: [ "8083:8083" ]
-    depends_on:
-      cassandra:
-        condition: service_healthy
-      cassandra-init:
-        condition: service_completed_successfully
+#    depends_on:
+#      cassandra:
+#        condition: service_healthy
+#      cassandra-init:
+#        condition: service_completed_successfully
     environment:
       - SERVER_PORT=8083
-      - JWT_SECRET=8MnKEjVM0ziVx5Bc9dHZcBgatpUtC7h9PB19ofa0GMK93OSb1DGbJtIy1Zj0DzrY
+      - JWT_SECRET=${JWT_SECRET}
+      - ASTRA_CLIENT_ID=${ASTRA_CLIENT_ID}
+      - ASTRA_CLIENT_SECRET=${ASTRA_CLIENT_SECRET}
 
   # payment-service:
   #   build: ./payment-service
@@ -105,30 +107,22 @@ services:
       - ALLOW_ANONYMOUS_LOGIN=yes
 
   kafka:
-    image: bitnami/kafka:latest
+    image: confluentinc/cp-kafka:7.5.0
+    container_name: kafka
     depends_on:
       - zookeeper
     ports:
       - "9092:9092"
     environment:
-#      - KAFKA_CFG_NODE_ID=1
-#      - KAFKA_CFG_PROCESS_ROLES=broker
-#      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
-#      - KAFKA_KRAFT_CLUSTER_ID=my-cluster-id
-#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
-#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
-#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
-#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
-#      - ALLOW_PLAINTEXT_LISTENER=yes
-      - KAFKA_ENABLE_KRAFT=no
-      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
-      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
-      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
-      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
-      - ALLOW_PLAINTEXT_LISTENER=yes
+      KAFKA_BROKER_ID: 1
+      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
+      #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
+      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
+      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
+      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
+      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
 
 volumes:
   mysql_data:
-  cassandra_data:
   kafka_data:
   # mongo_data:
